# frozen_string_literal: true

source 'https://rubygems.org'

ruby '3.3.0'

gem 'bcrypt', '~> 3.1.7'
gem 'bootsnap', require: false
gem 'groupdate'
gem 'pg'

gem 'puma', '>= 5.0'
gem 'rack-cors'
gem 'rails', '~> 7.1.3', '>= 7.1.3.2'
gem 'tzinfo-data', platforms: %i[windows jruby]

group :development, :test do
  gem 'debug', platforms: %i[mri windows]
  gem 'pg_query'
  gem 'prosopite'
  gem 'rubocop', require: false
  gem 'rubocop-performance', require: false
  gem 'rubocop-rails', require: false
  gem 'simplecov', require: false
end
